### ISSUE TITLE
intermittent "yum lockfile is held by another process" under ansible 2.8

### ISSUE THREAD

**Issue by earchibald-lv** [geerlingguy/ansible-role-nodejs#103]
I think your yum module calls might need the addition of `lock_timeout` to handle the changed behavior for ansible 2.8, per:

https://github.com/ansible/ansible/issues/57189

```
TASK [geerlingguy.nodejs : Add Nodesource repositories for Node.js (CentOS 7+).] *************************************************************************************************************************
fatal: [awx100.na6.oh1.livevox.net]: FAILED! => {"changed": false, "msg": "yum lockfile is held by another process"}
```

**Comment by geerlingguy** [comment]
I haven't had this issue running the role in a number of different builds. Is it possible you have two different automation tasks running concurrently, or someone is doing something manually on the server—or maybe you have automatic updates enabled and they're being triggered sometimes?

Basically, I'd like to know how I could reproduce this, and if you're seeing something happen every time or if it's just once in a while on your own servers.
