### ISSUE TITLE
Security: This role can lead to root compromission

### ISSUE THREAD

**Issue by maethor** [geerlingguy/ansible-role-nodejs#125]
In `tasks/main.yml` this role adds `npm.sh` in `/etc/profile.d`, which edit the PATH variable for all users.

As a result, `{{ npm_config_prefix }}/bin` is prepended to the PATH of the root user. But `{{ npm_config_prefix }}/bin` may not be owned by root, which gives power to an unprivileged user to override any binary and quickly gain root privileges.

**Comment by maethor** [comment]
I would suggest at least using the "$HOME" variable, and adding a condition, like what rbenv role is doing: https://github.com/zzet/rbenv/blob/master/templates/rbenv_user.sh.j2

**Comment by thbar** [comment]
Somehow related: https://github.com/geerlingguy/ansible-role-nodejs/pull/111

**Comment by geerlingguy** [comment]
See #111 — for convenience I'd rather keep the default so node things work okay (unless there's a better way of doing global installs nowadays?), but I think #111 would offer a good option for those who know what they're doing and want to avoid this pitfall.

**Comment by geerlingguy** [comment]
Workaround implemented in #111.
