### ISSUE TITLE
Nodesource repositories codename changed

### ISSUE THREAD

**Issue by oschwede** [geerlingguy/ansible-role-nodejs#153]
The Nodesource repositories unified their codenames and provide updates only for the new `nodistro` tag, which is supposed to be used across all supported operating systems.

With an existing installation of NodeJS 18 using this role, this change resulted in no further updates past 18.17.1 being installed. Newer versions up to 18.18 had not been offered for installation.

Further information: https://github.com/nodesource/distributions/blob/master/README.md#new-update-%EF%B8%8F

**Comment by geerlingguy** [comment]
Fixed with #155 above
