### ISSUE TITLE
Unable to install gulp as global package

### ISSUE THREAD

**Issue by jbouzekri** [geerlingguy/ansible-role-nodejs#17]
Hi,

I have this configuration : 

```
nodejs_npm_global_packages:
  - name: gulp
```

But the package won't install. This is the information coming from the playbook in debug mode : 

```
changed: [weenect.dev] => (item={u'name': u'gulp'}) => {"changed": true, "invocation": {"module_args": {"executable": null, "global": true, "ignore_scripts": false, "name": "gulp", "path": null, "production": false, "registry": null, "state": "latest", "version": ""}, "module_name": "npm"}, "item": {"name": "gulp"}}
```

Do you have any idea ? Is there something I am doing wrong ?

Thanks in advance

Regards

**Comment by geerlingguy** [comment]
Is it possible `gulp` is installed under the root account? Test by going to `sudo su` and checking if the root account has it available.

**Comment by jbouzekri** [comment]
No nothing.

```
root@debian-jessie:/home/vagrant# which gulp
root@debian-jessie:/home/vagrant# sudo npm list -g | grep gulp
root@debian-jessie:/home/vagrant# 
```

**Comment by geerlingguy** [comment]
Interesting... I've heard similar reports from some people using Drupal VM, so I'll try to figure out what's going on.

**Comment by jbouzekri** [comment]
Okay thanks. I will try to look into it this weekend too.

**Comment by oxyc** [comment]
Just realised this was happening on a my recent Drupal VM builds as well.

**Comment by geerlingguy** [comment]
This is a bug in the latest version of Ansible, see: https://github.com/ansible/ansible-modules-extras/issues/1375

Unfortunately this bug is present only when using `state=latest` for `npm` modules, and it only seems to affect Ubuntu distributions—see https://travis-ci.org/geerlingguy/ansible-role-nodejs/builds/110545132 :/

I'm trying to figure out a good workaround in the mean time.

**Comment by geerlingguy** [comment]
This has been fixed in the latest code: https://github.com/geerlingguy/ansible-role-nodejs/commit/459f3fed968a6b49eb0fcfe9542050433bab0a9d

I will roll a new tag with the fix for Galaxy as soon as I can verify the `nodejs_version` is applying correctly for CentOS/RHEL.

**Comment by jbouzekri** [comment]
Thanks @geerlingguy
