### ISSUE TITLE
RHEL/CentOS nodejs_version not working for 4.x, 5.x

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-nodejs#18]
After #16, it looks like 4.x and 5.x might not be working correctly for installing the right Node.js version. According to this test build (https://travis-ci.org/geerlingguy/ansible-role-nodejs/builds/110547868), 0.10 was installed on both CentOS 6 and 7 whereas 5.x was installed on Ubuntu :(

**Comment by FlxPeters** [comment]
https://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodesource-release-el6-1.noarch.rpm

The new default version 0.12 even isn't available anymore

**Comment by geerlingguy** [comment]
Hmm... https://rpm.nodesource.com/pub_0.12/el/6/x86_64/
