### ISSUE TITLE
Nodesource repo failure with CentOS 6 and Node.js 0.12

### ISSUE THREAD

**Issue by amidia** [geerlingguy/ansible-role-nodejs#21]
following my prior twit @abahmika this is the message i encounter when my vagrant stop
FAILED! => {"changed": false, "failed": true, "msg": "Package at https://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodesource-release-el6-1.noarch.rpm could not be installed", "rc": 1}
any solution guys?

**Comment by geerlingguy** [comment]
Here's an image of the error:

![abahmika_2016-mar-14](https://cloud.githubusercontent.com/assets/481677/13752424/a3915392-e9dc-11e5-88b3-f6f16895cb47.jpg)

**Comment by geerlingguy** [comment]
It's an upstream bug in https://github.com/nodesource/distributions/issues/240 - and please refer to #20. For now, my recommendations would be to use a different Node.js version (0.10 or 4.x would both work), or to switch to a CentOS 7 or Ubuntu base box; 0.12 is working in those.
