### ISSUE TITLE
fails to deploy on ubuntu due to missing apt-transport-https

### ISSUE THREAD

**Issue by ssbarnea** [geerlingguy/ansible-role-nodejs#22]
On Ubuntu it is mandatory to first do `apt-get install apt-transport-https` before installing any HTTPS based repository because apt-get update will fail, and you will endup with a system where apt-get is broken.

This case is clearly explained here http://askubuntu.com/a/211531/1004

**Comment by fanatique** [comment]
Same is true for Debian Jessy.

The problem can be solved by adding the following to `setup-Debian.yml`:

```YAML
- name: Check that HTTPS transport is available to APT
  apt: name="apt-transport-https" state=present
```
