### ISSUE TITLE
Support request: How do I change the install version of ruby?

### ISSUE THREAD

**Issue by pierremarcelio** [geerlingguy/ansible-role-nodejs#25]
I'm trying to change Ruby version form 1.9.3p484 to 2.x. How do I do that?

I see a node config version option `nodejs_version:`, but I don't see a way to change Ruby version.

Thanks!

**Comment by pierremarcelio** [comment]
Sorry wrong project, the DrupalTO camp guys distracted me! ;-)

**Comment by geerlingguy** [comment]
@pierremarcelio - No problem!
