### ISSUE TITLE
selecting node 5.x is limited to 5.11 - option to select different node source (apt) ?

### ISSUE THREAD

**Issue by KidA001** [geerlingguy/ansible-role-nodejs#27]
We locally develop with node `5.6.x` - deb.nodesource.com only supports `5.x` and installs `5.11`. Is it possible to select a different source for installing node, like apt?

**Comment by geerlingguy** [comment]
This is something I'd be willing to support. Nodesource has burned me a few times, so I'm not even married to them as the default.

**Comment by xtuc** [comment]
I'm having the same issue. What about downloading from https://nodejs.org/dist/ ?
I will PR.

**Comment by geerlingguy** [comment]
@xtuc - That would require building from source, correct? I'm not entirely opposed to allowing people to choose packages or build from source, but it seems nodesource is one of the only decent cross-platform package sources available (for apt/yum/dnf).

**Comment by xtuc** [comment]
These are binaries, available for different platforms. They still require to be added to the `PATH`.

**Comment by naterkane** [comment]
i'm running into the same general issue. 6.x is giving me 6.5, however i would like to be able to specify 6.4 due to some bugs in 6.5.

**Comment by michaelBenin** [comment]
@geerlingguy how would you feel about using nvm for this instead of relying on nodesource?

**Comment by geerlingguy** [comment]
@michaelBenin - I'm not 100% opposed to it... but using `nvm`, `rvm`, etc. in the past has burned me in other weird ways, mostly due to their weird concept of virtual environments and environment-variable-based runtime configuration.
