### ISSUE TITLE
RHEL 6 can't install default nodejs version 0.12

### ISSUE THREAD

**Issue by courtlandj** [geerlingguy/ansible-role-nodejs#32]
Can't use this role to install on RHEL 6 using the default settings of `nodejs_version: "0.12"`. Seems there is no such package as e.g. `https://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodesource-release-el6-1.noarch.rpm`. (nor i386)

The NodeSource readme seems to show that RHEL 6 is supported, and indeed there are plenty of RPM packages in the nodesource.com [directories](https://rpm.nodesource.com/pub_0.12/el/6/i386/), but none are named matching what is in setup-RedHat.yml.

**Comment by geerlingguy** [comment]
See dupe https://github.com/geerlingguy/ansible-role-nodejs/issues/20 — it's an upstream issue and there's a workaround (mentioned in #20), and I'm going to defer to nodesource on it.

**Comment by courtlandj** [comment]
Don't know if you care to look at my own solution: 477d034595d484dd9e0087471721d8ca5af5b912
