### ISSUE TITLE
index failed to download

### ISSUE THREAD

**Issue by naivefun** [geerlingguy/ansible-role-nodejs#33]
Ubuntu 16.04

http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/xenial/main/binary-i386/Packages is 404. Any fix?

**Comment by geerlingguy** [comment]
@naivefun - I generally only support x64 packages, as I don't have any 32-bit infrastructure anymore. What kind of project are you seeing this failure on? If it's a Vagrant box, try switching to a 64-bit version; or if it's a VM or something else, consider using the 64-bit version of the image.
