### ISSUE TITLE
Install fails on CentOS - incorrect nodesource repository

### ISSUE THREAD

**Issue by tomnewport** [geerlingguy/ansible-role-nodejs#35]
When run on CentOS 6.7, attempts to download the following nonexistant file from nodesource:

     https://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodesource-release-el6-1.noarch.rpm

This does not exist on nodesource.

**Comment by ProvAlison** [comment]
I see the same issue with CentOS 7.2 https://rpm.nodesource.com/pub_4.4.7/el/7/x86_64/nodesource-release-el7-1.noarch.rpm

**Comment by martinmenge** [comment]
Same issue on both CentOS 6 and 7. I believe I had an issues a few weeks back trying to install nodejs on a non vagrant CentOS machines and also ran into rpm issues. I didn't document it though

**Comment by belshire** [comment]
Was able to fix this by defining the node version I wanted installed in a generic way: nodejs_version: "6.x". The nodesource RPM repo doesn't have specific version numbers in the URLs for the 4, 5, or 6 versions of node. I don't think this will work for the 0.12 version though the URL for that version is the same that the nodesource install script generates.

**Comment by geerlingguy** [comment]
You have to use generic major version numbers for the `nodejs_version`, like 4.x, 5.x, or 6.x (see valid versions in the role's README for details).
