### ISSUE TITLE
missing repo gpg signing keys

### ISSUE THREAD

**Issue by ReSearchITEng** [geerlingguy/ansible-role-nodejs#37]
> https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL

`fatal: [xxxx]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "enablerepo": null, "exclude": null, "install_repoquery": true, "list": null, "name": ["https://rpm.nodesource.com/pub_5.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm"], "state": "present", "update_cache": false, "validate_certs": true}, "module_name": "yum"}, "msg": "**Failed to validate the SSL certificate for rpm.nodesource.com:443**. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}`

**Comment by geerlingguy** [comment]
Fixed by merging the PR, but note that CentOS 6 is still broken due to SNI being used in the Nodesource SSL certs via Cloudfront. (See: https://travis-ci.org/geerlingguy/ansible-role-nodejs/jobs/158842371#L295).
