### ISSUE TITLE
Suggestion: allow choice of node.js version

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/ansible-role-nodejs#4]
I want to make a suggestion for functionality like this:
 - https://github.com/nodesource/ansible-nodejs-role/commit/e6d6edd83b689a740a085da6cfeea960fd24852e

Feel free to decline, but it would be nice.

**Comment by geerlingguy** [comment]
I've heard the same request from a few other developers, so I'm going to go ahead and make this change.

**Comment by sarahjean** [comment]
Yeah, this would be super useful. ++

**Comment by geerlingguy** [comment]
There's a new `ansible_version` variable, and you can use `0.10` and `0.12` on Debian/Ubuntu, or `0.10` on RHEL (at least until https://github.com/nodesource/distributions/issues/73 is resolved). Apparently RHEL/CentOS is a second class citizen for now :(

**Comment by oxyc** [comment]
Just putting it out there, in the case of a development machine, using a version manager is vastly superior to `apt` or `yum`. Personally I prefer [tj/n](https://github.com/tj/n) as it doesn't require any profile modifications. Then there's also [creationix/nvm](https://github.com/creationix/nvm).

**Comment by geerlingguy** [comment]
@oxyc - This role is mainly targeted at building production servers/images (which I would typically recommend sticking on one stable version), and then mirroring that server/image in a local environment/image. For developers who work better with a workflow of one environment and multiple versions that can be used, using different solutions is definitely a better option.

**Comment by fubarhouse** [comment]
@oxyc I completely agree, but I also agree with@geerlingguy as this is a specific need which doesn't match that of the majority of Drupal users. It would add a lot of needless tasks into the playbook and most users wouldn't appreciate it.

It is a hassle to code up your own roles and test and what-not, but it's relatively easy if the logic is good. I've got my own public roles for this purpose for RVM and NVM - though they're not up to date with all my recent changes over the past couple of days. You can look on Ansible Galaxy, make your own, or even try out mine if you're game - just give feedback.
