### ISSUE TITLE
'ansible_user' is undefined

### ISSUE THREAD

**Issue by wasabigeek** [geerlingguy/ansible-role-nodejs#47]
Currently getting this error when running the role dependency:
==> default: TASK [nodejs : Define nodejs_install_npm_user] *********************************
==> default: fatal: [controller]: FAILED! => {"failed": true, "msg": "'ansible_user' is undefined"}

**Comment by ArondeParon** [comment]
@wasabigeek what was the problem? I have read the README several times now but do not see the problem.
