### ISSUE TITLE
How to install 4.5 on xenial, deb sources issues

### ISSUE THREAD

**Issue by enricostano** [geerlingguy/ansible-role-nodejs#50]
I've opened an issue here too https://github.com/nodesource/distributions/issues/372

Any idea?

I just set `nodejs_version: '4.5'`

Thanks!

**Comment by enricostano** [comment]
I see that I cannot choose the specific version... `4.x` means LITERALLY `4.x` XD

**Comment by geerlingguy** [comment]
Haha, yes... just '4.x' for the latest 4.x version, 5.x, etc.
