### ISSUE TITLE
Change default Node.js version to 4.x

### ISSUE THREAD

**Issue by fafnirical** [geerlingguy/ansible-role-nodejs#54]
Node.js 0.12 is currently in its maintenance phase, and will be unsupported after December 31, 2016, per the [LTS schedule](https://github.com/nodejs/LTS#lts-schedule).

Node.js 4.x should work on all supported platforms.

**Comment by geerlingguy** [comment]
👍  - I'll do it next time I get to this role in my routine maintenance, otherwise someone else can submit a PR.

**Comment by geerlingguy** [comment]
6.x is now the current LTS (https://github.com/nodejs/LTS), so I merged a PR to default to that version here: https://github.com/geerlingguy/ansible-role-nodejs/pull/58
