### ISSUE TITLE
Ansible_User is undefined when using SSH_CONFIG

### ISSUE THREAD

**Issue by cristian04** [geerlingguy/ansible-role-nodejs#59]
Im using the following ssh_config file

```
Host 192.168.1.1
  User ubuntu
  IdentityFile ~/.ssh/dev.pem
  ControlMaster auto
  ControlPersist 5m
```

However, the role is returning the following error 

```
TASK [geerlingguy.nodejs : Define nodejs_install_npm_user] *********************
Wednesday 22 February 2017  15:51:13 +1300 (0:00:02.855)       0:00:23.872 ****
fatal: [integration-worker]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible_user' is undefined\n\nThe error appears to have been in '/Users/cristian04/clearpoint/grability-playbooks/galaxy/geerlingguy.nodejs/tasks/main.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Define nodejs_install_npm_user\n  ^ here\n"}
```

**Expected result:** 
The role should pick the user on the ssh_config file

From https://github.com/ansible/ansible/issues/13982:

`ansible_user its not undefined, its null, that is how it is supposed to be. The connection itself will NOT pass a user to ssh, which then uses the current user, this is done to allow the use of .ssh/config when not specifying a user.`

**Comment by geerlingguy** [comment]
@cristian04 - Hmm... I'm not sure what to do here, then... I guess we could make that a default variable and default to `{{ ansible_user }}` so you can manually set it when you call the role?

I'm not quite sure how to get the user if you're defining the user solely through ssh_config.

**Comment by hepabolu** [comment]
Just tried this with the current version on Galaxy. 
ssh config sets user to 'ansible'. --> login is fine, error as above
'ansible_user' specifically set in inventory/hostname/main.yml --> same error
'nodejs_install_npm_user' set in inventory/hostname/main.yml --> same error
nodejs_install_npm_user set in playbook or in 'var_files' --> no error

I'm using Ansible 2.2.1.0 on OSX 10.11.6

**Comment by cristian04** [comment]
I've fixed this by using this

```
nodejs_install_npm_user: ubuntu 
```
in my `vars` files

**Comment by geerlingguy** [comment]
From https://github.com/ansible/ansible/issues/14195#issuecomment-176479117, I'm going to see if defaulting to the current `$USER` works okay; I'll add this to a new bugfix tag.
