### ISSUE TITLE
"Add nodesource" step fails due to invalid link on Amazon Linux

### ISSUE THREAD

**Issue by brandonrich** [geerlingguy/ansible-role-nodejs#6]
This returns a 404:
https://rpm.nodesource.com/pub/el/NA/x86_64/nodesource-release-elNA-1.noarch.rpm

Error specifics:
TASK: [nodejs | Add Nodesource repositories for Node.js.] ********************\* 
failed: [bi-portal-test.oit.nd.edu] => {"changed": false, "failed": true, "rc": 1}
msg: Package at https://rpm.nodesource.com/pub/el/NA/x86_64/nodesource-release-elNA-1.noarch.rpm could not be installed

**Comment by geerlingguy** [comment]
@brandonrich - Do you happen to have `gather_facts: no` or something like that in your playbook? Also, what OS / system / version are you on?

**Comment by brandonrich** [comment]
Failed on Amazon Linux (details below).  But just going to that link in a browser, you can see it's missing.  Gather facts was on.

$ uname -a
Linux ip-172-22-72-41 3.14.35-28.38.amzn1.x86_64 #1 SMP Wed Mar 11 22:50:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by geerlingguy** [comment]
@brandonrich - D'oh! Amazon Linux strikes again... Maybe I could make the URL overridable so those using Amazon Linux (which behaves awkwardly, since it's neither RHEL nor CentOS, but really it is) can manually supply a URL.

**Comment by geerlingguy** [comment]
It looks like Nodesource's own scripts do some strange things to try to map 'Amazon Linux' releases to the appropriate RedHat release... I don't know how simple it will be to make things automatic/easy and work with Amazon's flavor.

**Comment by geerlingguy** [comment]
Also as a quick note this is what it's trying to build:

```
name: "https://rpm.nodesource.com/{{ nodejs_rhel_rpm_dir }}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
```

And the problem is Amazon Linux spits out an oh-so-unhelpful `NA` for `ansible_distribution_major_version`.

**Comment by gabesmed** [comment]
note for all others seeing this issue: there's a workaround documented by @geerlingguy here: https://github.com/geerlingguy/ansible-role-repo-epel/issues/11
```
pre_tasks:
  - set_fact:
      ansible_distribution_major_version: "6"
```

**Comment by blackstar257** [comment]
Thanks for the solution @gabesmed

**Comment by WhiteyDude** [comment]
FYI, fixed in https://github.com/geerlingguy/ansible-role-nodejs/pull/101.

It also appears there are other 1+ year old pull requests attempting to solve the same thing.
