### ISSUE TITLE
Getting message 'The repository does not have a Release' file on Xenial

### ISSUE THREAD

**Issue by mvasin** [geerlingguy/ansible-role-nodejs#60]
I provision this role with default settings on Ubuntu 16.04 server and get this error:

```
TASK [nodejs : Add NodeSource PPA for latest version of Node.js.] **************
System info:
  Ansible 2.2.1.0; Darwin
  Trellis at "Forward extra bin/deploy.sh parameters to ansible-playbook"
---------------------------------------------------
MODULE FAILURE
Traceback (most recent call last):
  File "/tmp/ansible_JdB_w3/ansible_module_apt_repository.py", line 538, in
<module>
    main()
  File "/tmp/ansible_JdB_w3/ansible_module_apt_repository.py", line 527, in
main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 454, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:The repository 'http://ppa.launchpad.net
/chris-lea/node.js/ubuntu xenial Release' does not have a Release file.,
W:Data from such a repository can't be authenticated and is therefore
potentially dangerous to use., W:See apt-secure(8) manpage for repository
creation and user configuration details., E:Failed to fetch
http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/xenial/main/binary-
amd64/Packages  404  Not Found, E:Some index files failed to download. They
have been ignored, or old ones used instead.

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: W:The repository 'http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found, E:Some index files failed to download. They have been ignored, or old ones used instead.
fatal: [flops-staging]: FAILED! => {"changed": false, "failed": true, "module_stdout": ""}
```

**Comment by mvasin** [comment]
Maybe because xenial version is not there? I don't see it http://ppa.launchpad.net/chris-lea/node.js/ubuntu/

**Comment by mvasin** [comment]
This role worked for me: https://github.com/nodesource/ansible-nodejs-role

**Comment by geerlingguy** [comment]
@mvasin - I'm not sure where that's coming from, but it's definitely not from this role—this role uses `nodesource`'s own repo, not `chris-lea/node.js`, which is mentioned in that error message. I'm wondering if you might've either been using a really old role version, or have some other role that's adding in that PPA?

**Comment by geerlingguy** [comment]
Possibly related? https://github.com/geerlingguy/ansible-role-nodejs/issues/3

Note that I use this role in Drupal VM, and haven't had an issue on Ubuntu 16.04 in recent memory...

**Comment by issmirnov** [comment]
Facing same error when setting `nodejs_version: "4.2"`, running on a test instance with a fresh install of Ubuntu 16.04

**Comment by mvasin** [comment]
I had this in `requirements.yml`:
```
- name: nodejs
  src: geerlingguy.nodejs
  version: 1.1.0
```

That's because I copied and pasted the previous requirement I had in `requirements.yml` and forgot to change the version.

So I changed version and tried to `ansible-galaxy install -r`, but with no effect, galaxy didn't notice the difference. So I uninstalled the old version (`ansible-galaxy remove -p ./roles nodejs`), changed version to 4.0.0 in `requirements.yml` and installed the current version, but... still, I had the same error.

Then I removes `nodejs` role once again and put simple

`- src: geerlingguy.nodejs`

into `requirements.yml`. It installed with new name `geerlingguy.nodejs` (instead of `nodejs`) and my playbook finished this time without troubles!

Maybe it's cache bug that should be reported to ansible-galaxy project? But I didn't see any cache in action, both times when I was installing version 4.0.0 galaxy printed

```
- downloading role 'nodejs', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-nodejs/archive/4.0.0.tar.gz
- extracting nodejs to ./roles/nodejs
- nodejs was installed successfully
```
and I didn't have impression it was coming from cache, as it took some time in both cases.

At least, if you have the same scenario of installing older version, **the workaround is to update role version to the latest or remove completely AND change role name in `requirements.yml` to something different, then install the role once again**.

So far, I'll close the issue (as I opened it), but feel free to reopen it if my workaround doesn't work for you.

**Comment by AJamesPhillips** [comment]
I have a similar seemingly cache error.  I erroneously tried setting `nodejs_version: "8.1.0"` which failed with:

    failed: [255.___.___.255] (item=deb https://deb.nodesource.com/node_8.1.0 xenial main) => {"changed": false, "failed": true, "item": "deb https://deb.nodesource.com/node_8.1.0 xenial main", "module_stderr": "Shared connection to 255.___.___.255 closed.
    ", "module_stdout": "Traceback (most recent call last):
      File \"/tmp/ansible_2JpLYn/ansible_module_apt_repository.py\", line 565, in <module>
        main()
      File \"/tmp/ansible_2JpLYn/ansible_module_apt_repository.py\", line 553, in main
        cache.update()
      File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 454, in update
        raise FetchFailedException(e)
    apt.cache.FetchFailedException: W:The repository 'https://deb.nodesource.com/node_8.1.0 xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch https://deb.nodesource.com/node_8.1.0/dists/xenial/main/binary-amd64/Packages  404  Not Found, E:Some index files failed to download. They have been ignored, or old ones used instead.
    ", "msg": "MODULE FAILURE", "rc": 0}
    failed: [255.___.___.255] (item=deb-src https://deb.nodesource.com/node_8.1.0 xenial main) => {"changed": false, "failed": true, "item": "deb-src https://deb.nodesource.com/node_8.1.0 xenial main", "module_stderr": "Shared connection to 255.___.___.255 closed.
    ", "module_stdout": "Traceback (most recent call last):
      File \"/tmp/ansible_jTu3R9/ansible_module_apt_repository.py\", line 565, in <module>
        main()
      File \"/tmp/ansible_jTu3R9/ansible_module_apt_repository.py\", line 553, in main
        cache.update()
      File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 454, in update
        raise FetchFailedException(e)
    apt.cache.FetchFailedException: W:The repository 'https://deb.nodesource.com/node_8.1.0 xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch https://deb.nodesource.com/node_8.1.0/dists/xenial/main/source/Sources  404  Not Found, E:Some index files failed to download. They have been ignored, or old ones used instead.
    ", "msg": "MODULE FAILURE", "rc": 0}

Now regardless of the value of `nodejs_version: "..."` it always errors with a similar error (it's still trying and failing to look up the previously specified version):

    failed: [46.101.5.163] (item=deb https://deb.nodesource.com/node_6.x xenial main) => {"changed": false, "failed": true, "item": "deb https://deb.nodesource.com/node_6.x xenial main", "module_stderr": "Shared connection to 46.101.5.163 closed.
    ", "module_stdout": "Traceback (most recent call last):
      File \"/tmp/ansible_T5VYxE/ansible_module_apt_repository.py\", line 565, in <module>
        main()
      File \"/tmp/ansible_T5VYxE/ansible_module_apt_repository.py\", line 553, in main
        cache.update()
      File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 454, in update
        raise FetchFailedException(e)
    apt.cache.FetchFailedException: W:The repository 'https://deb.nodesource.com/node_8.1.0 xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch https://deb.nodesource.com/node_8.1.0/dists/xenial/main/source/Sources  404  Not Found, E:Some index files failed to download. They have been ignored, or old ones used instead.
    ", "msg": "MODULE FAILURE", "rc": 0}

Should we reopen this @mvasin / @geerlingguy ?

**Comment by AJamesPhillips** [comment]
It might be [coming from this line in ansible/os/apt](https://github.com/ansible/ansible/blob/1f7871584885a3a1652fd4f17cf7d5eb28e7d218/lib/ansible/modules/packaging/os/apt.py#L944) but I'm not certain.  Obviously the stack track above shows `ansible_module_apt_repository.py` but I can't find this file.

**Comment by geerlingguy** [comment]
It seems to be working in the Travis CI tests... https://travis-ci.org/geerlingguy/ansible-role-nodejs (set to run daily on cron)

**Comment by AJamesPhillips** [comment]
Thanks @geerlingguy understood.  Though the tests don't try to set an invalid value of `nodejs_version` and then set a valid one... that's how you can recreate this issue.  Unless you know how to clear the ansible apt cache on the target machine (I don't) you have to scrap the whole thing as it gets stuck looking up the old value regardless of any new `nodejs_version` value you use.
