### ISSUE TITLE
Add option do enable/disable role by single variable

### ISSUE THREAD

**Issue by aosmialowski** [geerlingguy/ansible-role-nodejs#7]
Howdy,

what do you think about following approach:

main.yml
```---
- include: nodejs.yml
  when: nodejs_enabled
  tags: [nodejs]
```

nodejs.yml
```
// Tasks here
```

I use the mentioned approach in my roles, works perfectly and helps to keep my playbooks really clear without any `when` conditionals. The `*_enabled` variable is being set up in `defaults/main.yml` file (my roles are disabled by default). Could create pull requests for your roles I'm using, but would like to know if you're going to accept those.

**Comment by geerlingguy** [comment]
It would be much simpler (and make the role not have to handle any extra logic) to do the following in your playbooks:

```yaml
- hosts: all
  roles:
    - name: geerlingguy.nodejs
      when: nodejs_enabled
```

That way every role doesn't have to add an extra file/indirection, and for the 99% of users who don't need to add a flag like _enabled, things remain the same. It should really be up to the playbook to determine when to use a role or not. If a role shouldn't be run, then nothing inside that role should be run.
