### ISSUE TITLE
The repository... does not have a Release file

### ISSUE THREAD

**Issue by ropedonkey** [geerlingguy/ansible-role-nodejs#72]
Installation fails (at least on xenial) with:

`The repository 'https://deb.nodesource.com/node_6.x xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use`

From what I can tell, this role uses the same repositories specified by nodesource for Manual installation.

Was working until yesterday (17th) as far as I'm aware. Is there a wider issue at nodesource perhaps? I find it odd that I can't find others reporting the same problem...

**Comment by jamesalford** [comment]
I also get this same issue.

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

- {role: geerlingguy.nodejs, nodejs_version: '4.x'}

TASK [geerlingguy.nodejs : Add NodeSource repositories for Node.js.] ************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: W:The repository 'https://deb.nodesource.com/node_4.4 xenial Release' does not have a Release file

**Comment by rosenstrauch** [comment]
i saw this error due to misconfigured dns settings. after changing the order of my dns servers provisioning continued beyond this point (but maybe i was just lucky).

**Comment by seenickcode** [comment]
I'm getting the same issues with Node 9.x. I'm setting this via:

`nodejs_version: "9.x"`

Error:

```
apt.cache.FetchFailedException: W:The repository 'https://deb.nodesource.com/node_9.0.0 xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., W:Skipping acquire of configured file 'stable/binary-i386/Packages' as repository 'https://download.docker.com/linux/ubuntu xenial InRelease' doesn't support architecture 'i386', E:Failed to fetch https://deb.nodesource.com/node_9.0.0/dists/xenial/main/source/Sources  404  Not Found, E:Some index files failed to download. They have been ignored, or old ones used instead.
```

Any quick fix @rosenstrauch ?

**Comment by thibaultlavoisey** [comment]
Same issue for `nodejs` and `yarn`.

**Comment by dawidpawlowski** [comment]
For me helps adding `pre_tasks` with updating apt cache:

```
  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes
```

**Comment by dsteinberger** [comment]
Hello, can we have an update to fix this please ? 
thanks

**Comment by geerlingguy** [comment]
I haven't had this issue... I'm wondering if it was something temporary maybe? Is anyone else still having this issue?

**Comment by ConnerAiken** [comment]
@geerlingguy, I just tried to use this role today and ran into this. Occurred with nodejs_version set to "9.x". Adding the apt cache update from your test-latest.yml fixed it for me though.

**Comment by geerlingguy** [comment]
@ConnerAiken Ah, in that case, I almost always—at least on Debian-based OSes—add an apt cache update task to the top of every playbook, instead of adding it into every single role I maintain. I would imagine that could be causing the issue for many if not most of the others in this issue?

I would rather not add the task to my role because apt cache management is not really this role's responsibility (IMO); it should be done at the playbook level (e.g. how it's done in the test playbooks this role uses).

**Comment by snrbrnjna** [comment]
Maybe add this to the Readme?

If you encounter problems that the nodejs binaries couldnt be found, something like this:

> `The repository 'https://deb.nodesource.com/node_6.x xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use`

Then add this to your playbook:
```yml
pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
```

**Comment by wassef911** [comment]
still having the same issue
