### ISSUE TITLE
nodejs_version: "0.12" fails

### ISSUE THREAD

**Issue by mehulkar** [geerlingguy/ansible-role-nodejs#8]
If I set `nodejs_version` to `"0.12"`, everything works fine, but with 0.12, it fails:

```
➜  provisioning git:(master) ✗ ansible-playbook playbook.yml -i inventory -u centos

PLAY [basic] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [staging]

TASK: [geerlingguy.nodejs | Make sure nodejs_version is set correctly.] ******* 
failed: [staging] => {"assertion": "nodejs_version == \"0.10\"", "evaluated_to": false, "failed": true}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/mehulkar/playbook.retry

staging                    : ok=1    changed=0    unreachable=0    failed=1   
```

I'm new to Ansible though, so it's possible I'm using it wrong.

**Comment by mehulkar** [comment]
guessing the `assert` is causing that here:

https://github.com/geerlingguy/ansible-role-nodejs/blob/master/tasks/setup-RedHat.yml#L4

Is this intentional?

**Comment by geerlingguy** [comment]
Yes; unfortunately, the Nodesource repository currently doesn't host the `0.12` version for RedHat/CentOS; see https://github.com/nodesource/distributions/issues/73

For now, I have this noted in the role's README file under the `nodejs_version` variable, and I'll update it once the issue gets fixed upstream.
