### ISSUE TITLE
Installing @angular/cli

### ISSUE THREAD

**Issue by Copser** [geerlingguy/ansible-role-nodejs#84]
Hello,

have a small question regarding installing `npm` packages. I need to install `@angular/cli` globally before I install `package.json`.

As you can see the problem is the name I can't install

```
name: "@anguar/cli"
version: 6.0.8
```

or for that matter

```
name: angular-cli
version: 6.0.8
```

so is there a way that I can do this?

**Comment by CloudSurgeon** [comment]
I was able to successfully install @angular/cli:

```
nodejs_npm_global_packages:
        - '@angular/cli'
```

so perhaps try using single quotes in your dictionary.

**Comment by Copser** [comment]
Hey, sorry for the late response, yes this is how you install the cli, will close the issue.
