### ISSUE TITLE
chgrp failed: failed to look up group

### ISSUE THREAD

**Issue by wonderchang** [geerlingguy/ansible-role-nodejs#91]
I got the error

```
{"changed": false, "gid": 0, "group": "root", "mode": "0755", "msg": "chgrp failed: failed to look up group myuser", "owner": "myuser", "path": "/usr/local/lib/npm", "size": 4096, "state": "directory", "uid": 9058}
```

In my scenario, for some management policy reasons, the ssh-agent user's name and group are not the same.

https://github.com/geerlingguy/ansible-role-nodejs/blob/48ba494b41bbefab26bb25f3e57382d8bb70099f/tasks/main.yml#L17

Is it possible to make `group` adjustable?

**Comment by mamedin** [comment]
I found the same issue when the ssh-agent user's name and group are not the same.
