### ISSUE TITLE
Fails to install on Centos 7

### ISSUE THREAD

**Issue by kokarn** [geerlingguy/ansible-role-nodejs#96]
Trying both `nodejs_version: "10.x"` and `nodejs_version: "8.x"` fails with 

`No package matching 'nodejs-10.*' found available, installed or updated` 
and
`No package matching 'nodejs-8.*' found available, installed or updated` respectively.

Is there something wrong with the repo perhaps?

**Comment by jbowen7** [comment]
There's an open pull request that addresses your issue: #95
Here's a patch if you can't wait for upstream
[setup-RedHat.yml.patch.gz](https://github.com/geerlingguy/ansible-role-nodejs/files/3119265/setup-RedHat.yml.patch.gz)

**Comment by getjack** [comment]
@geerlingguy #95 has been merged but i still happen to have the problem. Was the commit already released? Else this issue would be a duplicate i guess.

**Comment by glaszig** [comment]
i've had a very similar problem. the issue is an outdated yum cache. merging #107 might resolve your issue, too.

**Comment by ki0** [comment]
bump!
