### ISSUE TITLE
Global packages doesn't use nodejs_install_npm_user?

### ISSUE THREAD

**Issue by dianomi-mjs** [geerlingguy/ansible-role-nodejs#97]
Hi

Trying to use this role to install nodejs plus some packages

    - {
        role: geerlingguy.nodejs,
        nodejs_install_npm_user: "root",
        nodejs_npm_global_packages: [node-sass, puppeteer]
      }

And getting errors like this

TASK [geerlingguy.nodejs : Ensure npm global packages are installed.] ****************************
task path: /home/mjs/.ansible/roles/geerlingguy.nodejs/tasks/main.yml:26
failed: [hostname] (item=node-sass) => {"changed": false, "cmd": "/bin/npm install --global ''", "item": "node-sass", "msg": "Unable to save binary /usr/local/lib/npm/lib/node_modules/node-sass/vendor/linux-x64-64 :********@4.12.0 postinstall script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2019-05-23T09_33_20_090Z-debug.log

Not an expert by any means but there shouldn't be permission errors installing if I'm root. But looking at https://github.com/geerlingguy/ansible-role-nodejs/blob/master/tasks/main.yml it seems perhaps the package installation doesn't use the nodejs_install_npm_user?

**Comment by apg036** [comment]
I have the same issue. Even trying to use npm manually gives the same permission error:

```
# npm install -g jfrog-cli-go

> jfrog-cli-go@1.25.0 preinstall /usr/local/lib/npm/lib/node_modules/jfrog-cli-go
> node init.js


┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
Downloading JFrog CLI 1.25.0
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open 'bin/jfrog'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jfrog-cli-go@1.25.0 preinstall: `node init.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jfrog-cli-go@1.25.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-24T12_55_07_113Z-debug.log
```


[2019-05-24T12_55_07_113Z-debug.log](https://github.com/geerlingguy/ansible-role-nodejs/files/3216944/2019-05-24T12_55_07_113Z-debug.log)

**Comment by kingispeak** [comment]
The same problem.

**Comment by fullofcaffeine** [comment]
Same issue :(

**Comment by pvanhemmen** [comment]
I can confirm this issue

**Comment by icaliman** [comment]
Same issue
